Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

===== RESTART: C:/Users/bayan/Desktop/my codes/Automation/cropmanyimages.py ====
Beige White .jpg
Blue .jpg
Coffee Photo .jpg
Cream .jpg
Desktop Wallpaper.jpg
Gray .jpg
Green.jpg
ocean.jpg
Pink Flower.jpg
sea.jpg
>>> 
===== RESTART: C:/Users/bayan/Desktop/my codes/Automation/cropmanyimages.py ====
Enter Cropping Width : 300
Enter Cropping Height : 300
Enter Folder Name : Test
Traceback (most recent call last):
  File "C:\Users\bayan\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\Image.py", line 2390, in save
    format = EXTENSION[ext]
KeyError: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/bayan/Desktop/my codes/Automation/cropmanyimages.py", line 21, in <module>
    im1.save(f"{output_folder}/image")
  File "C:\Users\bayan\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\Image.py", line 2393, in save
    raise ValueError(msg) from e
ValueError: unknown file extension: 
>>> 
===== RESTART: C:/Users/bayan/Desktop/my codes/Automation/cropmanyimages.py ====
Enter Cropping Width : 300
Enter Cropping Height : 300
Enter Folder Name : Test
>>> 
===== RESTART: C:/Users/bayan/Desktop/my codes/Automation/cropmanyimages.py ====
Enter Cropping Width : 600
Enter Cropping Height : 800
Enter Folder Name : Test2
>>> 
==== RESTART: C:/Users/bayan/Desktop/my codes/Automation/cropmanyimages2.py ====
Enter Fit Size : 500
Enter Folder Name : Test3
